### ISSUE TITLE
you are bad

### ISSUE THREAD

**Issue by weinbee** [armi-ne/Electric-SkateBot-Python#4]
![bitmoji](https://render.bitstrips.com/v2/cpanel/27b025e9-96e0-4fb8-af6d-50d0d1281753-64942b8f-00c2-40d9-9a44-d2393b6ae4cc-v1.png?transparent=1&palette=1&width=246)

plz stop

**Comment by armi-ne** [comment]
Thank you for the bug report. I'm sure it's client side however I'll have a deeper look into the issue. In the meantime could I suggest: "No, u"?

Regards, Armin

**Comment by weinbee** [comment]
Thanks! Great bot. A+
